version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: curas-postgres
    environment:
      POSTGRES_DB: curas_dev
      POSTGRES_USER: curas
      POSTGRES_PASSWORD: localdev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
