name: Deploy React Frontend to S3 + Invalidate CloudFront

on:
  push:
    branches:
      - main

env:
  BUILD_DIR: dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies with Bun
        run: bun install

      - name: Inject environment variables
        run: |
          echo "VITE_API_URL=${{ secrets.DEV_VITE_API_URL }}" >> .env
          echo "VITE_COGNITO_CLIENT_ID=${{ secrets.DEV_VITE_COGNITO_CLIENT_ID }}" >> .env
          echo "VITE_COGNITO_REDIRECT_URI=${{ secrets.DEV_VITE_COGNITO_REDIRECT_URI }}" >> .env
          echo "VITE_COGNITO_RESPONSE_TYPE=${{ secrets.DEV_VITE_COGNITO_RESPONSE_TYPE }}" >> .env
          echo "VITE_COGNITO_SCOPE=${{ secrets.DEV_VITE_COGNITO_SCOPE }}" >> .env
          echo "VITE_COGNITO_AUTHORITY=${{ secrets.DEV_VITE_COGNITO_AUTHORITY }}" >> .env
          echo "VITE_DOMAIN=${{ secrets.DEV_VITE_DOMAIN }}" >> .env
          echo "VITE_ENVIRONMENT=${{ secrets.DEV_VITE_ENVIRONMENT }}" >> .env

      - name: Build with Bun
        run: bun run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ${{ env.BUILD_DIR }}

      - name: CloudFront Cache Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }}
